### ISSUE TITLE
Make sure that API key is unique

### ISSUE THREAD

**Issue by henrywintif** [henrywinn/beerAPI#9]
Check the db to make sure api key given to user is unique

**Comment by henrywintif** [comment]
Maybe look at UserAPI.post(). I'm actually checking in two ways for both email and username. The db.search() method looks a lot nicer than the try: but the try around the db.get() is probably more efficient.

Documentation for the db class can be found at https://orchestrate.io/docs/clients/python

**Comment by runverzagt** [comment]
I feel like a better place for it might be in Keychain.create_user_key(), because that way the non-unique key can be rejected between the time that it's created (:62) and the time it's put into the database (:63). Does that make sense?

**Comment by henrywintif** [comment]
Definitely agree with that.

**Comment by runverzagt** [comment]
Do we have any way to test the code? I'm not sure if my fix will work, check it out at 19eb8a345859bee86e4330ef2637bc02dd8a1390

**Comment by runverzagt** [comment]
@henrywinn provide some feedback on my fix. Specifically with regard to what the returned statement from Orchestrate is.

**Comment by runverzagt** [comment]
I just realized that we really have no way to test this, since an api key collision would be totally random and impossible to intentionally recreate.

Therefore I'm going to assume my fix worked and mark this issue as closed.

**Comment by henrywintif** [comment]
Haha, good point
